package visual;

import algo.roughset.ClassicRoughSet;
import algo.roughset.missing.MissingRoughSet;
import algo.roughset.RoughSet;
import algo.roughset.SimilarityRoughSet;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author zero
 */
public class MainFrame extends javax.swing.JFrame {
    private String currentDirectory;
    private RoughSet roughSet;
    private double delta;
    
    public MainFrame() {
        initComponents();
        
        buttonGroup.add(simRadioButton);
        buttonGroup.add(classicalRadioButton);
        buttonGroup.add(missingRadioButton);
        classicalRadioButton.setSelected(true);
        
        attrTextField.setEnabled(false);
        desClassCheckBox.setSelected(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        loadButton = new javax.swing.JButton();
        classicalRadioButton = new javax.swing.JRadioButton();
        simRadioButton = new javax.swing.JRadioButton();
        missingRadioButton = new javax.swing.JRadioButton();
        desClassCheckBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        attrTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadButton.setText("Cargar Archivo");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        classicalRadioButton.setText("Teoria Clasica");
        classicalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicalRadioButtonActionPerformed(evt);
            }
        });

        simRadioButton.setText("Basada en Similitud");

        missingRadioButton.setText("Valores Omitidos");

        desClassCheckBox.setText("Usar Ultimo Atributo como de Desicion");
        desClassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desClassCheckBoxActionPerformed(evt);
            }
        });

        attrTextField.setPreferredSize(new java.awt.Dimension(10, 24));
        attrTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attrTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Atributo de Decision");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classicalRadioButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(attrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(desClassCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(simRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(missingRadioButton)
                                .addGap(166, 166, 166))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(loadButton)
                                .addGap(31, 31, 31))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classicalRadioButton)
                    .addComponent(simRadioButton)
                    .addComponent(missingRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addComponent(loadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desClassCheckBox)
                    .addComponent(attrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        JFileChooser fileChooser;
        
        if( currentDirectory == null )
            fileChooser = new JFileChooser();
        else 
            fileChooser = new JFileChooser(currentDirectory);
        
        fileChooser.approveSelection();
        fileChooser.setDialogTitle("Seleccione el archivo .arff");
        
        if( fileChooser.showDialog(this, "Cargar") == JFileChooser.APPROVE_OPTION ){
            int attr = -1;
            String file = fileChooser.getSelectedFile().toString();
            
            if( !desClassCheckBox.isSelected() )
                attr = Integer.parseInt(attrTextField.getText());
            
            try{
                if( classicalRadioButton.isSelected() ){
                    if( desClassCheckBox.isSelected() )
                        roughSet = new ClassicRoughSet(file);
                    else
                        roughSet = new ClassicRoughSet(file, attr);
                }
                else if( missingRadioButton.isSelected() ){
                    if( desClassCheckBox.isSelected() )
                        roughSet = new MissingRoughSet(file);
                    else
                        roughSet = new MissingRoughSet(file, attr);
                }
                else{
                    SimFrame simFrame = new SimFrame();
                    simFrame.setLocationRelativeTo(null);
                    simFrame.setVisible(true);
                    
                    if( desClassCheckBox.isSelected() )
                        roughSet = new SimilarityRoughSet(file, simFrame.getDelta());
                    else
                        roughSet = new SimilarityRoughSet(file, attr, simFrame.getDelta());
                }
            } 
            catch (IOException ex) {
                JOptionPane.showMessageDialog(
                        this, 
                        "Error al cargar el archivo!", 
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                        this, 
                        "Error al procesar el indice del atributo!", 
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
            catch(IllegalArgumentException iee){
                    JOptionPane.showMessageDialog(
                        this, 
                        iee.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
            
    }//GEN-LAST:event_loadButtonActionPerformed

    private void classicalRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicalRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classicalRadioButtonActionPerformed

    private void attrTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attrTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attrTextFieldActionPerformed

    private void desClassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desClassCheckBoxActionPerformed
        attrTextField.setEnabled(!desClassCheckBox.isSelected());
    }//GEN-LAST:event_desClassCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attrTextField;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton classicalRadioButton;
    private javax.swing.JCheckBox desClassCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loadButton;
    private javax.swing.JRadioButton missingRadioButton;
    private javax.swing.JRadioButton simRadioButton;
    // End of variables declaration//GEN-END:variables
}
