/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import cibercafe.ExistingUserException;
import utils.Utils;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JTextField;
import users.User;
import users.EventualUser;

/**
 *
 * @author luis
 */
public class AddUserFrame extends javax.swing.JFrame {
    private static MainFrame caller;
    
    /**
     * Creates new form AddUserFrame
     * @param caller
     */
    public AddUserFrame(MainFrame caller) {
        initComponents();
        
        listCategories.setEnabled(false);
        finalizeButtonAddUser.setEnabled(false);
        yearsTextField.setEnabled(false);
        addAnotherButton.setEnabled(false);
        
        this.caller = caller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkBoxAddUser = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCategories = new javax.swing.JList();
        nameTextField = new javax.swing.JTextField();
        cardTextField = new javax.swing.JTextField();
        finalizeButtonAddUser = new javax.swing.JButton();
        cancelButtonAddUser = new javax.swing.JButton();
        yearsTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addAnotherButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir un usuario");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Tarjeta de Crédito:");

        checkBoxAddUser.setText("Asociado");
        checkBoxAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAddUserActionPerformed(evt);
            }
        });

        listCategories.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCategories);

        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        cardTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTextFieldActionPerformed(evt);
            }
        });
        cardTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cardTextFieldKeyReleased(evt);
            }
        });

        finalizeButtonAddUser.setText("Finalizar");
        finalizeButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeButtonAddUserActionPerformed(evt);
            }
        });

        cancelButtonAddUser.setText("Cancelar");
        cancelButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonAddUserActionPerformed(evt);
            }
        });

        yearsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsTextFieldActionPerformed(evt);
            }
        });
        yearsTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearsTextFieldKeyReleased(evt);
            }
        });

        jLabel3.setText("Años de Servicio");

        addAnotherButton.setText("Añadir Otro");
        addAnotherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnotherButtonActionPerformed(evt);
            }
        });

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalizeButtonAddUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkBoxAddUser))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(yearsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(cardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAnotherButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButtonAddUser))
                    .addComponent(ImageLabel))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxAddUser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizeButtonAddUser)
                    .addComponent(cancelButtonAddUser)
                    .addComponent(addAnotherButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAddUserActionPerformed
        listCategories.setEnabled(getCheckBoxAddUser().isSelected());    
        getYearsTextField().setEnabled(getCheckBoxAddUser().isSelected());
        finalizeButtonAddUser.setEnabled(canEnableFinalize());
        addAnotherButton.setEnabled(canEnableFinalize());
    }//GEN-LAST:event_checkBoxAddUserActionPerformed

    private void cardTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTextFieldActionPerformed

    private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
        finalizeButtonAddUser.setEnabled(canEnableFinalize());
        addAnotherButton.setEnabled(canEnableFinalize());
    }//GEN-LAST:event_nameTextFieldKeyReleased

    private void cardTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardTextFieldKeyReleased
        finalizeButtonAddUser.setEnabled(canEnableFinalize());
        addAnotherButton.setEnabled(canEnableFinalize());
    }//GEN-LAST:event_cardTextFieldKeyReleased

    private void listCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCategoriesValueChanged
        finalizeButtonAddUser.setEnabled(canEnableFinalize());
        addAnotherButton.setEnabled(canEnableFinalize());
    }//GEN-LAST:event_listCategoriesValueChanged

    private void finalizeButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeButtonAddUserActionPerformed
        User user = null;
        
        try{
            if( getCheckBoxAddUser().isSelected() )
                user = caller.main.registerAsociatedUserFromAddUserFrame(this);
            else
                user = new EventualUser(getNameTextField().getText(), getCardTextField().getText(), -1);
        
            caller.main.enQueueUser(user);
            dispose();
        }
        catch(ExistingUserException eue){
            caller.main.launchErrorDialog(this, eue);
        }
    }//GEN-LAST:event_finalizeButtonAddUserActionPerformed

    private void yearsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsTextFieldActionPerformed
        
    }//GEN-LAST:event_yearsTextFieldActionPerformed

    private void yearsTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearsTextFieldKeyReleased
        finalizeButtonAddUser.setEnabled(canEnableFinalize());
        addAnotherButton.setEnabled(canEnableFinalize());
    }//GEN-LAST:event_yearsTextFieldKeyReleased

    private void cancelButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonAddUserActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonAddUserActionPerformed

    private void addAnotherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnotherButtonActionPerformed
        User user = null;
        
        try{
            if( getCheckBoxAddUser().isSelected() )
                user = caller.main.registerAsociatedUserFromAddUserFrame(this);
            else
                user = new EventualUser(getNameTextField().getText(), getCardTextField().getText(), -1);
        
            caller.main.enQueueUser(user);
            
            nameTextField.setText("");
            cardTextField.setText("");
            yearsTextField.setText("");
            checkBoxAddUser.setSelected(false);
            yearsTextField.setEnabled(false);
            listCategories.setEnabled(false);
            finalizeButtonAddUser.setEnabled(false);            
            addAnotherButton.setEnabled(false);            
        }
        catch(ExistingUserException eue){
            caller.main.launchErrorDialog(this, eue);
        }
    }//GEN-LAST:event_addAnotherButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUserFrame addUser = new AddUserFrame(caller);
             
                addUser.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JButton addAnotherButton;
    private javax.swing.JButton cancelButtonAddUser;
    private javax.swing.JTextField cardTextField;
    private javax.swing.JCheckBox checkBoxAddUser;
    private javax.swing.JButton finalizeButtonAddUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listCategories;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField yearsTextField;
    // End of variables declaration//GEN-END:variables

    private boolean canEnableFinalize(){
        boolean flag = true;
        
        flag &= Utils.areAllDigits(getCardTextField().getText());
        flag &= !nameTextField.getText().equals("");
        
        if( getCheckBoxAddUser().isSelected() ){
            flag &= Utils.isNonNegativeInteger(getYearsTextField().getText());
            flag &= !listCategories.isSelectionEmpty();
        }
        
        return flag;
    } 

    public JList getList(){ return listCategories; }
    public JCheckBox getCheckBox(){ return getCheckBoxAddUser(); }
    public JTextField getCardTextField() { return cardTextField; }
    public JCheckBox getCheckBoxAddUser() { return checkBoxAddUser; }
    public JTextField getNameTextField() { return nameTextField; }
    public JTextField getYearsTextField() { return yearsTextField; }    
}
